# Generated by Django 5.1.6 on 2025-04-06 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0002_address_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmodule.address'),
        ),
    ]
