# Generated by Django 5.1.6 on 2025-04-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0004_card_course_department_remove_student_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
