# Generated by Django 5.1.6 on 2025-04-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0005_delete_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
