# Generated by Django 5.1.6 on 2025-04-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0010_company_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expire_year',
            field=models.IntegerField(),
        ),
    ]
