# Generated by Django 5.1.6 on 2025-04-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0013_address1_student1_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmodule.address1'),
        ),
    ]
