# Generated by Django 5.1.6 on 2025-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0014_alter_student1_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.SmallIntegerField(default=1)),
                ('pic', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
