# Generated by Django 5.1.6 on 2025-04-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0015_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='pic',
            new_name='pictuer',
        ),
    ]
