# Generated by Django 5.1.6 on 2025-04-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0016_rename_pic_register_pictuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='pictuer',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
