# Generated by Django 5.1.6 on 2025-04-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0017_alter_register_pictuer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='pictuer',
        ),
        migrations.AddField(
            model_name='register',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
