# Generated by Django 5.1.6 on 2025-04-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0019_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='register1',
        ),
    ]
