# Generated by Django 5.1.6 on 2025-04-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0020_rename_register_register1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register1',
            name='picture',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
