# Generated by Django 5.1.6 on 2025-04-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0021_alter_register1_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
